Repository slackhq/vitess, pull requests merged in 2023-05, with the labels that each got.

#73 `slack-vitess-r14.0.5` Backport vitessio/vitess#11167-vtgate buffer fix
  go/flags/endtoend/vtgate.txt
  go/mysql/auth_server_clientcert_test.go
  go/mysql/client_test.go
  go/mysql/conn.go
  go/mysql/fakesqldb/server.go
  go/mysql/handshake_test.go
  go/mysql/query_benchmark_test.go
  go/mysql/server.go
  go/mysql/server_flaky_test.go
  go/vt/vtgate/plugin_mysql_server.go
Labels: v14, upstream-backport

#74 `slack-vitess-r14.0.5` bump up package versions for cve/snyk tickets
  go.mod
  go.sum
Labels: security, v14

#75 `slack-vitess-r14.0.5:`Backport upstream vitessio/12007
  go/vt/vitessdriver/rows.go
  go/vt/vitessdriver/rows_test.go
Labels: v14, upstream-backport

#81 `slack-vitess-r14.0.5-dsdefense`: backport vitessio/vitess#12949
  go/mysql/sql_error.go
  go/mysql/sql_error_test.go
Labels: v14, upstream-backport, dsdefense

#80 `slack-vitess-r14.0.5:`Implement the Vitess Structure Logger VTSLogger
  go.mod
  go.sum
  go/flags/endtoend/vtgate.txt
  go/flags/endtoend/vttablet.txt
  go/vt/logutil/vts_logger.go
  go/vt/logutil/vts_logger_test.go
  go/vt/servenv/grpc_auth.go
  go/vt/servenv/grpc_server_auth_mtls.go
  go/vt/servenv/grpc_server_auth_static.go
  go/vt/servenv/servenv.go
Labels: v14, upstream-wip

#83 `slack-vitess-r14.0.5-dsdefense`: backport `txthrottler` cleanup PR vitessio/vitess#12901
  go/vt/vttablet/tabletserver/txthrottler/tx_throttler.go
  go/vt/vttablet/tabletserver/txthrottler/tx_throttler_test.go
Labels: upstream-backport, txthrottler, v14-dsdefense

#84 Add vstream metrics to vtgate (#13098)
  go/vt/vtgate/vstream_manager.go
  go/vt/vtgate/vstream_manager_test.go
Labels: v14, upstream-backport, slack-cherrypick, cla:signed
