Repository slackhq/vitess, pull requests merged in 2024-05, with the labels that each got.

#321 [v14.0.5]: Backport upstream 13856 - reshard state check fix
  go.mod
  go.sum
  go/test/utils/noleak.go
  go/vt/discovery/keyspace_events.go
  go/vt/discovery/keyspace_events_test.go
  go/vt/topo/topoproto/srvkeyspace.go
Labels: v14, upstream-backport

#258 `slack-vitess-r15.0.5`: backport v16 `vtorc` fixes
  go.mod
  go.sum
  go/cmd/vtorc/status.go
  go/flags/endtoend/vtbackup.txt
  go/flags/endtoend/vtctld.txt
  go/flags/endtoend/vtgate.txt
  go/flags/endtoend/vtgr.txt
  go/flags/endtoend/vtorc.txt
  go/flags/endtoend/vttablet.txt
  go/internal/flag/flag.go
  go/test/endtoend/reparent/newfeaturetest/reparent_test.go
  go/test/endtoend/reparent/plannedreparent/reparent_test.go
  go/test/endtoend/vtorc/api/api_test.go
  go/test/endtoend/vtorc/primaryfailure/primary_failure_test.go
  go/test/endtoend/vtorc/readtopologyinstance/main_test.go
  go/vt/topo/locks.go
  go/vt/topo/locks_test.go
  go/vt/vtctl/reparentutil/emergency_reparenter.go
  go/vt/vtctl/reparentutil/replication.go
  go/vt/vtctl/reparentutil/replication_test.go
  go/vt/vtorc/attributes/attributes.go
  go/vt/vtorc/attributes/attributes_dao.go
  go/vt/vtorc/config/config.go
  go/vt/vtorc/config/config_test.go
  go/vt/vtorc/db/db.go
  go/vt/vtorc/db/generate_base.go
  go/vt/vtorc/db/generate_patches.go
  go/vt/vtorc/inst/analysis_dao.go
  go/vt/vtorc/inst/analysis_dao_test.go
  go/vt/vtorc/inst/audit_dao.go
  go/vt/vtorc/inst/audit_dao_test.go
  go/vt/vtorc/inst/cluster.go
  go/vt/vtorc/inst/cluster_domain_dao.go
  go/vt/vtorc/inst/downtime_dao.go
  go/vt/vtorc/inst/instance.go
  go/vt/vtorc/inst/instance_dao.go
  go/vt/vtorc/inst/instance_dao_test.go
  go/vt/vtorc/inst/minimal_instance.go
  go/vt/vtorc/inst/tablet_dao.go
  go/vt/vtorc/logic/orchestrator.go
  go/vt/vtorc/logic/tablet_discovery.go
  go/vt/vtorc/logic/tablet_discovery_test.go
  go/vt/vtorc/logic/topology_recovery.go
  go/vt/vtorc/logic/topology_recovery_dao.go
  go/vt/vtorc/logic/topology_recovery_dao_test.go
  go/vt/vtorc/server/api.go
  go/vt/vtorc/test/recovery_analysis.go
Labels: upstream-backport, cla:missing, vtorc, v16-backport, v15

#356 `slack-vitess-r15.0.5`: fix races in `Unit Test (Race)` CI, fix "old" reparent CIs
  .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml
  .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml
  go.mod
  go/flags/endtoend/vtbackup.txt
  go/flags/endtoend/vtctld.txt
  go/flags/endtoend/vtgate.txt
  go/flags/endtoend/vtgr.txt
  go/flags/endtoend/vtorc.txt
  go/flags/endtoend/vttablet.txt
  go/flags/endtoend/vttestserver.txt
  go/internal/flag/flag.go
  go/test/endtoend/reparent/plannedreparent/reparent_test.go
  go/vt/servenv/exporter.go
  go/vt/topo/consultopo/server.go
  go/vt/vttest/topoctl.go
Labels: bug, v15

#361 `slack-vitess-r15.0.5`: misc required backports, pt. 1
  go/vt/servenv/servenv.go
  go/vt/vitessdriver/rows.go
  go/vt/vitessdriver/rows_test.go
  go/vt/vtctl/grpcvtctldserver/server_test.go
  go/vt/vtgate/vstream_manager.go
  go/vt/vtgate/vstream_manager_test.go
  go/vt/vttablet/tabletserver/vstreamer/engine.go
  go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
Labels: upstream-backport, cla:missing, v16-backport, v15, v17-backport, v19-backport

#367 `slack-15.0`: fix private repo git config in docker build
  docker/base/Dockerfile.mariadb
  docker/base/Dockerfile.mariadb103
  docker/base/Dockerfile.mysql80
  docker/base/Dockerfile.percona57
  docker/base/Dockerfile.percona80
Labels: v15

#375 `slack-15.0`: refactor private go dep config from #367
  build.env
  docker/base/Dockerfile.mariadb
  docker/base/Dockerfile.mariadb103
  docker/base/Dockerfile.mysql80
  docker/base/Dockerfile.percona57
  docker/base/Dockerfile.percona80
Labels: v15

#371 `slack-15.0`: backport required Transaction Throttler PRs, pt. 4
  go/mysql/sql_error.go
  go/mysql/sql_error_test.go
  go/vt/throttler/max_replication_lag_module.go
  go/vt/throttler/max_replication_lag_module_test.go
Labels: upstream-backport, txthrottler, v15, v17-backport, v19-backport

#372 `slack-15.0`: Fallback to poller replication lag if heartbeat lag fails
  go/vt/vttablet/tabletserver/repltracker/repltracker.go
  go/vt/vttablet/tabletserver/repltracker/repltracker_test.go
Labels: slack-cherrypick, v15, upstream-me, deprecate

#377 `slack-15.0`: backport `vtgate` buffer fix vitessio/vitess#13856
  examples/local/scripts/vtgate-up.sh
  go/vt/discovery/keyspace_events.go
  go/vt/discovery/keyspace_events_test.go
  go/vt/topo/topoproto/srvkeyspace.go
Labels: upstream-backport, cla:missing, v15, v18-backport, v17-backport

#380 `slack-15.0`: VStreams fix backports/patches, pt. 2
  go/test/endtoend/vreplication/vreplication_test.go
  go/vt/discovery/tablet_picker.go
  go/vt/discovery/tablet_picker_test.go
  go/vt/proto/vtgate/vtgate.pb.go
  go/vt/proto/vtgate/vtgate_vtproto.pb.go
  go/vt/vtgate/endtoend/vstream_test.go
  go/vt/vtgate/vstream_manager.go
  go/vt/vtgate/vstream_manager_test.go
  go/vt/vttablet/tabletmanager/vdiff/table_differ.go
  go/vt/vttablet/tabletmanager/vreplication/controller.go
  go/vt/vttablet/tabletmanager/vreplication/controller_test.go
  go/vt/vttablet/tabletserver/vstreamer/copy.go
  go/vt/vttablet/tabletserver/vstreamer/uvstreamer.go
  go/vt/vttablet/tabletserver/vstreamer/uvstreamer_flaky_test.go
  go/vt/vttablet/tabletserver/vstreamer/vstreamer_flaky_test.go
  go/vt/wrangler/traffic_switcher.go
  go/vt/wrangler/traffic_switcher_env_test.go
  go/vt/wrangler/vdiff.go
  proto/vtgate.proto
  tools/rowlog/rowlog.go
Labels: upstream-backport, slack-cherrypick, cla:missing, v15, vstreams, upstream-me, v17-backport, v19-backport

#382 `slack-15.0`: basic go.mod updates
  go.mod
  go.sum
  go/flags/endtoend/mysqlctl.txt
  go/flags/endtoend/mysqlctld.txt
  go/flags/endtoend/vtaclcheck.txt
  go/flags/endtoend/vtbackup.txt
  go/flags/endtoend/vtctlclient.txt
  go/flags/endtoend/vtctld.txt
  go/flags/endtoend/vtctldclient.txt
  go/flags/endtoend/vtexplain.txt
  go/flags/endtoend/vtgate.txt
  go/flags/endtoend/vtgr.txt
  go/flags/endtoend/vtorc.txt
  go/flags/endtoend/vttablet.txt
  go/flags/endtoend/vttestserver.txt
  go/flags/endtoend/zkctl.txt
  go/flags/endtoend/zkctld.txt
  go/stats/statsd/statsd_test.go
  go/test/endtoend/vtgate/keyspace_watches/keyspace_watch_test.go
  go/vt/mysqlctl/azblobbackupstorage/azblob.go
Labels: security, v15

#384 `slack-15.0`: backport vitessio/vitess#15772
  go/vt/vtgate/vstream_manager.go
  go/vt/vtgate/vstream_manager_test.go
  go/vt/vttablet/sandboxconn/sandboxconn.go
Labels: upstream-backport, v15, v20-backport, vstreams
