Repository slackhq/vitess, pull requests merged in 2024-07, with the labels that each got.

#432 Backport 13856 - resharding error fix
  examples/local/scripts/vtgate-up.sh
  go/vt/discovery/keyspace_events.go
  go/vt/discovery/keyspace_events_test.go
  go/vt/topo/topoproto/srvkeyspace.go
Labels: cla:missing

#446 `slack-19.0`: disable `--config-file-not-found-handling` on v15 tests, remove `mysql57` CI
  .github/workflows/cluster_endtoend_backup_pitr_mysql57.yml
  .github/workflows/cluster_endtoend_backup_pitr_xtrabackup_mysql57.yml
  .github/workflows/cluster_endtoend_onlineddl_ghost_mysql57.yml
  .github/workflows/cluster_endtoend_onlineddl_revert_mysql57.yml
  .github/workflows/cluster_endtoend_onlineddl_scheduler_mysql57.yml
  .github/workflows/cluster_endtoend_onlineddl_vrepl_mysql57.yml
  .github/workflows/cluster_endtoend_onlineddl_vrepl_stress_mysql57.yml
  .github/workflows/cluster_endtoend_onlineddl_vrepl_stress_suite_mysql57.yml
  .github/workflows/cluster_endtoend_onlineddl_vrepl_suite_mysql57.yml
  .github/workflows/cluster_endtoend_schemadiff_vrepl_mysql57.yml
  .github/workflows/cluster_endtoend_tabletmanager_tablegc_mysql57.yml
  .github/workflows/cluster_endtoend_vtorc_mysql57.yml
  .github/workflows/cluster_endtoend_xb_backup_mysql57.yml
  .github/workflows/cluster_endtoend_xb_recovery_mysql57.yml
  .github/workflows/unit_test_mysql57.yml
  examples/common/env.sh
  test.go
  test/ci_workflow_gen.go
Labels: v19

#449 `slack-19.0`: add structured logging
  go.mod
  go.sum
  go/flags/endtoend/mysqlctl.txt
  go/flags/endtoend/mysqlctld.txt
  go/flags/endtoend/vtcombo.txt
  go/flags/endtoend/vtctld.txt
  go/flags/endtoend/vtgate.txt
  go/flags/endtoend/vtgateclienttest.txt
  go/flags/endtoend/vtorc.txt
  go/flags/endtoend/vttablet.txt
  go/flags/endtoend/vttestserver.txt
  go/vt/logutil/logger.go
  go/vt/logutil/logger_test.go
  go/vt/servenv/servenv.go
Labels: cla:missing, upstream-me, custom-patch, v19

#451 `slack-15.0`: fix crash in `vtbench`
  go/cmd/vtbench/vtbench.go
Labels: v15, custom-patch

#456 `slack-19.0`: fix docker base build + git private repo
  docker/base/Dockerfile
  docker/base/Dockerfile.mysql57
  docker/base/Dockerfile.percona57
  docker/base/Dockerfile.percona80
Labels: custom-patch, v19

#459 `slack-19.0`: v20 backports, pt. 2
  go/flags/endtoend/vtcombo.txt
  go/flags/endtoend/vtgate.txt
  go/flags/endtoend/vttablet.txt
  go/streamlog/streamlog.go
  go/streamlog/streamlog_test.go
  go/vt/discovery/healthcheck.go
  go/vt/discovery/topology_watcher.go
  go/vt/discovery/topology_watcher_test.go
  go/vt/vtgate/plugin_mysql_server_test.go
  go/vt/vtgate/vtgate.go
  go/vt/vttablet/tabletserver/query_engine.go
  go/vt/vttablet/tabletserver/query_engine_test.go
  go/vt/vttablet/tabletserver/query_executor.go
Labels: upstream-backport, v20-backport, v19

#460 `slack-15.0`: fix broken CI due to `percona-xtrabackup-24` repo problem
  .github/workflows/codeql_analysis.yml
  .github/workflows/upgrade_downgrade_test_backups_e2e.yml
  .github/workflows/upgrade_downgrade_test_backups_e2e_next_release.yml
  .github/workflows/upgrade_downgrade_test_backups_manual.yml
  .github/workflows/upgrade_downgrade_test_backups_manual_next_release.yml
  .github/workflows/upgrade_downgrade_test_query_serving_queries.yml
  .github/workflows/upgrade_downgrade_test_query_serving_queries_next_release.yml
  .github/workflows/upgrade_downgrade_test_query_serving_schema.yml
  .github/workflows/upgrade_downgrade_test_query_serving_schema_next_release.yml
  .github/workflows/upgrade_downgrade_test_reparent_new_vtctl.yml
  .github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml
  .github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml
  .github/workflows/upgrade_downgrade_test_reparent_old_vttablet.yml
  test/templates/cluster_endtoend_test_mysql57.tpl
  test/templates/dockerfile.tpl
Labels: v15, custom-patch

#442 `slack-15.0`: reset semi-sync in `setReplicationSourceRepairReplication`
  go/vt/vttablet/tabletmanager/rpc_replication.go
Labels: v15, custom-patch

#457 add keyrange support for vtorc clusters_to_watch
  go/flags/endtoend/vtorc.txt
  go/vt/vtorc/logic/tablet_discovery.go
  go/vt/vtorc/logic/tablet_discovery_test.go
Labels: upstream-me, custom-patch, v19
