Repository slackhq/vitess, pull requests merged in 2024-11, with the labels that each got.

#554 Patch: disable extensive keyspace events logging
  go/vt/discovery/keyspace_events.go
  go/vt/vtgate/buffer/shard_buffer.go
Labels: upstream-me, v19

#553 Patch: disable extensive keyspace events logging
  go/vt/discovery/keyspace_events.go
  go/vt/vtgate/buffer/shard_buffer.go
Labels: v15, upstream-me

#555 `slack-19.0`: backport `vtorc` optimisations, pt. 1
  go/flags/endtoend/vtorc.txt
  go/vt/external/golib/sqlutils/dialect.go
  go/vt/external/golib/sqlutils/sqlite_dialect.go
  go/vt/external/golib/sqlutils/sqlite_dialect_test.go
  go/vt/topo/keyspace.go
  go/vt/topo/shard.go
  go/vt/topo/tablet.go
  go/vt/topo/tablet_test.go
  go/vt/vtorc/db/db.go
  go/vt/vtorc/inst/analysis_dao.go
  go/vt/vtorc/inst/audit_dao.go
  go/vt/vtorc/inst/instance_dao.go
  go/vt/vtorc/inst/instance_dao_test.go
  go/vt/vtorc/logic/disable_recovery.go
  go/vt/vtorc/logic/tablet_discovery.go
  go/vt/vtorc/logic/topology_recovery_dao.go
  go/vt/vtorc/process/election_dao.go
  go/vt/vtorc/process/health_dao.go
Labels: upstream-backport, vtorc, v19, v22-backport

#564 [release-19.0] Fix to prevent stopping buffering prematurely (#17013)…
  go/test/endtoend/reparent/newfeaturetest/reparent_test.go
  go/test/endtoend/reparent/utils/utils.go
  go/vt/discovery/fake_healthcheck.go
  go/vt/discovery/keyspace_events.go
  go/vt/discovery/keyspace_events_test.go
  go/vt/vtgate/buffer/buffer.go
  go/vt/vtgate/buffer/buffer_helper_test.go
  go/vt/vtgate/buffer/buffer_test.go
  go/vt/vtgate/buffer/shard_buffer.go
  go/vt/vtgate/buffer/variables_test.go
  go/vt/vtgate/tabletgateway.go
  go/vt/vtgate/tabletgateway_flaky_test.go
Labels: v22-backport

#567 backport upstream 16655 - Fix race condition that prevents queries from being buffered after vtgate startup
  go/vt/discovery/keyspace_events.go
  go/vt/discovery/keyspace_events_test.go
  go/vt/srvtopo/discover.go
  go/vt/srvtopo/discover_test.go
  go/vt/vtgate/tabletgateway.go
  go/vt/vtgate/tabletgateway_flaky_test.go
  go/vt/vtgate/tabletgateway_test.go
Labels: cla:missing
