Repository slackhq/vitess, pull requests merged in 2024-10, with the labels that each got.

#514 Backport 14693 - Use GetTabletsByCell in healthcheck
  go/vt/discovery/healthcheck.go
  go/vt/discovery/tablet_picker.go
  go/vt/discovery/topology_watcher.go
  go/vt/discovery/topology_watcher_test.go
  go/vt/topo/consultopo/error.go
  go/vt/topo/errors.go
  go/vt/topo/etcd2topo/error.go
  go/vt/topo/memorytopo/file.go
  go/vt/topo/memorytopo/memorytopo.go
  go/vt/topo/shard.go
  go/vt/topo/tablet.go
  go/vt/topo/tablet_test.go
  go/vt/topo/zk2topo/error.go
  go/vt/topotools/tablet.go
  go/vt/topotools/utils.go
  go/vt/vtctl/grpcvtctldserver/server.go
  go/vt/vtctl/grpcvtctldserver/topo.go
  go/vt/wrangler/shard.go
  go/vt/wrangler/split.go
Labels: upstream-backport, v15, v19-backport, Component: VTGate, Component: VTTablet, Component: Query Serving, Type: Performance

#525 `slack-15.0`: Add sql text counts stats to `vtcombo`,`vtgate`+`vttablet` (vitessio#15897)
  go/vt/vtgate/vtgate.go
Labels: upstream-backport, v15-backport, v20-backport

#526 `slack-19.0`: backport `txthrottler` fixes from v21
  go/vt/discovery/healthcheck.go
  go/vt/discovery/healthcheck_test.go
  go/vt/discovery/keyspace_events_test.go
  go/vt/discovery/topology_watcher_test.go
  go/vt/throttler/demo/throttler_demo.go
  go/vt/throttler/replication_lag_cache.go
  go/vt/throttler/replication_lag_cache_test.go
  go/vt/throttler/throttler.go
  go/vt/throttler/throttler_test.go
  go/vt/vtgate/tabletgateway.go
  go/vt/vttablet/tabletserver/txthrottler/tx_throttler.go
  go/vt/vttablet/tabletserver/txthrottler/tx_throttler_test.go
Labels: upstream-backport, txthrottler, v19, v21-backport, Component: VTGate, Component: VTTablet, Type: Throttler

#510 backport: fixing issue with xtrabackup and long gtids (#16304)
  go/vt/mysqlctl/xtrabackupengine.go
  go/vt/mysqlctl/xtrabackupengine_test.go
Labels: upstream-backport, v15, v21-backport

#530 Fix healthcheck filters
  go/vt/discovery/healthcheck.go
  go/vt/discovery/topology_watcher_test.go
Labels: bug, Stale, v15, Component: VTTablet, Component: Throttler

#533 `slack-19.0`: skip `vexplain`/`schematracker` tests in downgrade e2e tests
  go/test/endtoend/vtgate/queries/vexplain/vexplain_test.go
  go/test/endtoend/vtgate/schematracker/sharded/st_sharded_test.go
  go/test/endtoend/vtgate/schematracker/unsharded/st_unsharded_test.go
Labels: v19

#532 `slack-19.0`: fix structured logging
  go/flags/endtoend/mysqlctl.txt
  go/flags/endtoend/mysqlctld.txt
  go/flags/endtoend/vtcombo.txt
  go/flags/endtoend/vtctld.txt
  go/flags/endtoend/vtgate.txt
  go/flags/endtoend/vtgateclienttest.txt
  go/flags/endtoend/vtorc.txt
  go/flags/endtoend/vttablet.txt
  go/flags/endtoend/vttestserver.txt
  go/vt/logutil/logger.go
  go/vt/logutil/logger_test.go
  go/vt/servenv/servenv.go
  go/vt/servenv/servenv_unix.go
  go/vt/servenv/servenv_windows.go
Labels: upstream-me, v19

#537 `slack-19.0`: update `slackhq/vitess-addons` to `v0.19.3`
  go.mod
  go.sum
  go/vt/vtorc/logic/topology_recovery.go
Labels: v19

#539 `slack-19.0`: vtorc: Switch to Vitess stats (#15948)
  go.mod
  go.sum
  go/vt/vtorc/inst/analysis_dao.go
  go/vt/vtorc/inst/analysis_dao_test.go
  go/vt/vtorc/inst/audit_dao.go
  go/vt/vtorc/inst/instance_dao.go
  go/vt/vtorc/logic/vtorc.go
Labels: upstream-backport, cla:missing, v20-backport, v19

#544 `slack-19.0`: backport v19 backport of vitessio/vitess PR #17077
  go/vt/vtgate/planbuilder/operators/plan_query.go
  go/vt/vtgate/planbuilder/testdata/select_cases.json
Labels: upstream-backport, v19-backport, v19, Component: VTGate, Type: Query Serving

#545 `slack-19.0`: optimize `sqlutils.ToSqlite3Dialect`
  go/vt/external/golib/sqlutils/sqlite_dialect.go
  go/vt/external/golib/sqlutils/sqlite_dialect_test.go
Labels: upstream-me, v19, Component: VTOrc

#546 `slack-19.0`: optimize `sqlutils.ToSqlite3Dialect`, part 2
  go/vt/external/golib/sqlutils/sqlite_dialect.go
  go/vt/external/golib/sqlutils/sqlite_dialect_test.go
  go/vt/vtorc/db/db.go
Labels: upstream-backport, v19, v22-backport

#548 Bugfix for Panic on Joined Queries with Non-Authoritative Tables in V…
  go/vt/vtgate/planbuilder/testdata/from_cases.json
  go/vt/vtgate/semantics/analyzer_test.go
  go/vt/vtgate/semantics/early_rewriter.go
  go/vt/vtgate/semantics/early_rewriter_test.go
Labels: cla:missing, v19-backport, v19
