Repository slackhq/vitess, pull requests merged in 2024-06, with the labels that each got.

#389 `slack-15.0`: backport vitessio/vitess#15897
  go/vt/vtgate/vtgate.go
  go/vt/vttablet/tabletserver/query_engine.go
  go/vt/vttablet/tabletserver/query_engine_test.go
  go/vt/vttablet/tabletserver/query_executor.go
Labels: upstream-backport, cla:missing, v15, v20-backport

#394 `slack-15.0`: v20 backports, pt. 2
  go/flags/endtoend/vtgate.txt
  go/flags/endtoend/vttablet.txt
  go/streamlog/streamlog.go
  go/streamlog/streamlog_flaky_test.go
  go/vt/discovery/healthcheck.go
  go/vt/discovery/topology_watcher.go
  go/vt/discovery/topology_watcher_test.go
  go/vt/vtgate/vtgate.go
  go/vt/vttablet/tabletserver/query_engine.go
  go/vt/vttablet/tabletserver/query_engine_test.go
Labels: upstream-backport, v15, v20-backport

#405 `slack-15.0`: Add timeout to all the contexts used for RPC calls in vtorc (#15991)
  go/vt/vtorc/logic/tablet_discovery.go
  go/vt/vtorc/logic/tablet_discovery_test.go
Labels: upstream-backport, cla:missing, vtorc, v15, v20-backport

#427 vtgate tablet balancer
  go/flags/endtoend/vtgate.txt
  go/vt/vtgate/balancer/balancer.go
  go/vt/vtgate/balancer/balancer_test.go
  go/vt/vtgate/tabletgateway.go
  go/vt/vtgate/vtgate.go
Labels: v14, upstream-me, custom-patch

#433 slack-15.0: vtgate tablet balancer
  go/flags/endtoend/vtgate.txt
  go/vt/vtgate/balancer/balancer.go
  go/vt/vtgate/balancer/balancer_test.go
  go/vt/vtgate/tabletgateway.go
  go/vt/vtgate/vtgate.go
Labels: v15-backport, v15, upstream-me, custom-patch
