Repository slackhq/vitess, pull requests merged in 2024-08, with the labels that each got.

#488 patch hnr grpc size flags
  go/flags/endtoend/vtgate.txt
  go/flags/endtoend/vttablet.txt
  go/vt/grpcclient/client.go
  go/vt/grpccommon/options.go
  go/vt/servenv/grpc_server.go
Labels: v14, upstream-me

#492 `slack-15.0`: support v17+ `--queryserver-config-*` duration values
  .github/workflows/unit_race.yml
  go/flags/endtoend/vttablet.txt
  go/flagutil/flagutil.go
  go/flagutil/flagutil_test.go
  go/mysql/fakesqldb/server.go
  go/vt/vtctl/grpcvtctldserver/server.go
  go/vt/vtctl/grpcvtctldserver/server_test.go
  go/vt/vttablet/tabletserver/tabletenv/config.go
Labels: cla:missing, v15, custom-patch

#480 `slack-15.0`: pre-backport `txthrottler` crash fixes
  go/vt/discovery/healthcheck.go
  go/vt/discovery/healthcheck_test.go
  go/vt/discovery/keyspace_events_test.go
  go/vt/throttler/demo/throttler_demo.go
  go/vt/throttler/manager.go
  go/vt/throttler/manager_test.go
  go/vt/throttler/max_replication_lag_module.go
  go/vt/throttler/replication_lag_cache.go
  go/vt/throttler/replication_lag_cache_test.go
  go/vt/throttler/result.go
  go/vt/throttler/result_test.go
  go/vt/throttler/throttler.go
  go/vt/throttler/throttler_test.go
  go/vt/throttler/throttlerclienttest/throttlerclient_testsuite.go
  go/vt/throttler/throttlerlogz.go
  go/vt/throttler/throttlerlogz_test.go
  go/vt/vtctld/vtctld.go
  go/vt/vtgate/tabletgateway.go
  go/vt/vttablet/tabletserver/txthrottler/mock_throttler_test.go
  go/vt/vttablet/tabletserver/txthrottler/tx_throttler.go
  go/vt/vttablet/tabletserver/txthrottler/tx_throttler_test.go
Labels: upstream-backport, v15, v21-backport

#496 balancer flags renamed to match upstream
  go/flags/endtoend/vtgate.txt
  go/vt/vtgate/tabletgateway.go
Labels: v15-backport, v15, custom-patch
