Repository slackhq/vitess, pull requests merged in 2025-08, with the labels that each got.

#681 add optional flag to enable multi shard autocommit by default
  go/flags/endtoend/vtcombo.txt
  go/flags/endtoend/vtgate.txt
  go/vt/vtexplain/vtexplain_vtgate.go
  go/vt/vtgate/engine/dml.go
  go/vt/vtgate/engine/fake_vcursor_test.go
  go/vt/vtgate/engine/insert.go
  go/vt/vtgate/engine/insert_select.go
  go/vt/vtgate/engine/primitive.go
  go/vt/vtgate/engine/send.go
  go/vt/vtgate/executor.go
  go/vt/vtgate/executor_framework_test.go
  go/vt/vtgate/executor_select_test.go
  go/vt/vtgate/executor_stream_test.go
  go/vt/vtgate/vcursor_impl.go
  go/vt/vtgate/vtgate.go
Labels: upstream-me

#682 [Bugfix] Broken Heartbeat system in Row Streamer (#18390)
  go/vt/vttablet/tabletserver/vstreamer/rowstreamer.go
  go/vt/vttablet/tabletserver/vstreamer/rowstreamer_test.go
Labels: cla:signed, v23-backport

#687 `slack-19.0`: allow vtorc recoveries to be disabled from startup (#18005)
  go/flags/endtoend/vtorc.txt
  go/test/endtoend/vtorc/readtopologyinstance/main_test.go
  go/vt/vtorc/config/config.go
  go/vt/vtorc/logic/vtorc.go
Labels: upstream-backport, v19, v23-backport

#677 `slack-19.0`: support a minority of lagging tablets in ERS
  go/vt/vtctl/reparentutil/emergency_reparenter.go
  go/vt/vtctl/reparentutil/emergency_reparenter_test.go
  go/vt/vtctl/reparentutil/reparent_sorter.go
  go/vt/vtctl/reparentutil/reparent_sorter_test.go
  go/vt/vtctl/reparentutil/replication.go
  go/vt/vtctl/reparentutil/replication_test.go
  go/vt/vtctl/reparentutil/util.go
  go/vt/vtctl/reparentutil/util_test.go
Labels: upstream-backport, v19, v23-backport

#705 [release-19.0] VReplication: Address SwitchTraffic bugs around replic…
  go/test/endtoend/vreplication/cluster_test.go
  go/test/endtoend/vreplication/vreplication_test.go
  go/vt/vtctl/workflow/server.go
  go/vt/vtctl/workflow/stream_migrator.go
  go/vt/vtctl/workflow/switcher.go
  go/vt/vtctl/workflow/switcher_dry_run.go
  go/vt/vtctl/workflow/switcher_interface.go
  go/vt/vtctl/workflow/traffic_switcher.go
Labels: v22-backport
