Repository slackhq/vitess, pull requests merged in 2025-04, with the labels that each got.

#632 Backport vstream copy fixes
  go/vt/vtgate/vstream_manager.go
  go/vt/vtgate/vstream_manager_test.go
Labels: cla:missing, v22-backport

#629 `slack-19.0`: backport additional `vtorc` stats from vitessio/vitess#17977
  go/vt/vtorc/logic/tablet_discovery.go
  go/vt/vtorc/logic/topology_recovery.go
  go/vt/vtorc/logic/vtorc.go
  go/vt/vtorc/logic/vtorc_test.go
Labels: upstream-backport, v22-backport, Component: VTOrc

#638 `slack 19.0`: pre backport vitessio/vitess#18152
  go/vt/topo/consultopo/server.go
  go/vt/topo/consultopo/server_flaky_test.go
Labels: upstream-backport, Component: VTGate, Component: VTTablet, Component: VTOrc, Component: VTCtld, v23-backport

#643 `slack-19.0`: update `github.com/golang/glog` to `v1.2.4`
  go.mod
  go.sum
Labels: security, custom-patch, v19

#645 `slack-19.0`: use `slackhq/vitess-addons@v0.19.9`
  go.mod
  go.sum
  go/vt/vtorc/logic/topology_recovery.go
Labels: custom-patch, v19
