Repository slackhq/vitess, pull requests merged in 2025-02, with the labels that each got.

#596 `slack-19.0`: various backports for `vtorc`, part 2
  go/flags/endtoend/vtbackup.txt
  go/flags/endtoend/vtcombo.txt
  go/flags/endtoend/vtctld.txt
  go/flags/endtoend/vtgate.txt
  go/flags/endtoend/vtorc.txt
  go/flags/endtoend/vttablet.txt
  go/test/endtoend/vtorc/api/api_test.go
  go/vt/discovery/healthcheck.go
  go/vt/discovery/topology_watcher.go
  go/vt/discovery/topology_watcher_test.go
  go/vt/external/golib/sqlutils/sqlutils.go
  go/vt/key/key.go
  go/vt/topo/keyspace.go
  go/vt/topo/server.go
  go/vt/topo/shard.go
  go/vt/topo/shard_test.go
  go/vt/topo/stats_conn.go
  go/vt/topo/stats_conn_test.go
  go/vt/topo/tablet.go
  go/vt/topo/tablet_test.go
  go/vt/vtorc/db/generate_base.go
  go/vt/vtorc/inst/instance_dao.go
  go/vt/vtorc/inst/instance_dao_test.go
  go/vt/vtorc/logic/keyspace_shard_discovery.go
  go/vt/vtorc/logic/keyspace_shard_discovery_test.go
  go/vt/vtorc/logic/tablet_discovery.go
  go/vt/vtorc/logic/tablet_discovery_test.go
  go/vt/vtorc/logic/vtorc.go
  go/vt/vtorc/logic/vtorc_test.go
  go/vt/vtorc/process/health.go
  go/vt/vtorc/process/health_test.go
  go/vt/vtorc/server/api.go
Labels: upstream-backport, cla:missing, vtorc, v20-backport, v22-backport

#599 `slack-19.0`: `vtorc`: improve handling of partial cell topo results
  go/vt/topo/faketopo/faketopo.go
  go/vt/vtorc/logic/tablet_discovery.go
  go/vt/vtorc/logic/tablet_discovery_test.go
Labels: bug, upstream-backport, v22-backport

#606 `slack-19.0`: Add stats for shards watched by VTOrc
  go/vt/vtorc/inst/shard_dao.go
  go/vt/vtorc/inst/shard_dao_test.go
  go/vt/vtorc/logic/keyspace_shard_discovery.go
Labels: upstream-backport, v22-backport

#604 backport/patch connection pool bug/perf fixes
  go/pools/smartconnpool/connection.go
  go/pools/smartconnpool/pool.go
  go/pools/smartconnpool/pool_test.go
  go/pools/smartconnpool/stack.go
  go/pools/smartconnpool/timestamp.go
  go/pools/smartconnpool/waitlist.go
Labels: cla:missing, v19, v22-backport

#609 backport 17818: pool: reopen connection closed by idle timeout (#17818)
  go/pools/smartconnpool/pool.go
  go/pools/smartconnpool/pool_test.go
Labels: cla:missing, v22-backport

#610 `slack-21.0`: backport v22 VTOrc fixes, part 1
  go/flags/endtoend/vtbackup.txt
  go/flags/endtoend/vtcombo.txt
  go/flags/endtoend/vtctld.txt
  go/flags/endtoend/vtgate.txt
  go/flags/endtoend/vtorc.txt
  go/flags/endtoend/vttablet.txt
  go/vt/discovery/healthcheck.go
  go/vt/discovery/topology_watcher.go
  go/vt/discovery/topology_watcher_test.go
  go/vt/external/golib/sqlutils/dialect.go
  go/vt/external/golib/sqlutils/sqlite_dialect.go
  go/vt/external/golib/sqlutils/sqlite_dialect_test.go
  go/vt/key/key.go
  go/vt/log/log.go
  go/vt/topo/faketopo/faketopo.go
  go/vt/topo/keyspace.go
  go/vt/topo/server.go
  go/vt/topo/shard.go
  go/vt/topo/shard_test.go
  go/vt/topo/stats_conn.go
  go/vt/topo/stats_conn_test.go
  go/vt/topo/tablet.go
  go/vt/topo/tablet_test.go
  go/vt/vtorc/db/db.go
  go/vt/vtorc/inst/analysis_dao.go
  go/vt/vtorc/inst/audit_dao.go
  go/vt/vtorc/inst/instance_dao.go
  go/vt/vtorc/inst/instance_dao_test.go
  go/vt/vtorc/inst/shard_dao.go
  go/vt/vtorc/inst/shard_dao_test.go
  go/vt/vtorc/logic/disable_recovery.go
  go/vt/vtorc/logic/keyspace_shard_discovery.go
  go/vt/vtorc/logic/keyspace_shard_discovery_test.go
  go/vt/vtorc/logic/tablet_discovery.go
  go/vt/vtorc/logic/tablet_discovery_test.go
  go/vt/vtorc/logic/topology_recovery.go
  go/vt/vtorc/logic/topology_recovery_dao.go
  go/vt/vtorc/logic/topology_recovery_dao_test.go
  go/vt/vtorc/logic/topology_recovery_test.go
  go/vt/vtorc/process/health.go
Labels: upstream-backport, cla:missing, v22-backport, v21

#613 `slack-19.0`: backport v22 VTOrc optimizations, part 2
  go/vt/vtorc/db/generate_base.go
  go/vt/vtorc/inst/instance_dao.go
  go/vt/vtorc/inst/tablet_dao.go
Labels: upstream-backport, v19, v22-backport
