Repository slackhq/vitess, pull requests merged in 2025-03, with the labels that each got.

#616 `slack-19.0`: backport finalized version of v22 PR vitessio/vitess#17815
  go/vt/vtorc/inst/shard_dao_test.go
  go/vt/vtorc/logic/keyspace_shard_discovery.go
  go/vt/vtorc/logic/keyspace_shard_discovery_test.go
Labels: upstream-backport, v19, v22-backport, Component: VTOrc

#618 `slack-19.0` backport v22 `vtorc` optimizations + stats, part 3
  go/flags/endtoend/vtorc.txt
  go/vt/vtorc/collection/collection.go
  go/vt/vtorc/collection/collection_test.go
  go/vt/vtorc/config/config.go
  go/vt/vtorc/db/db.go
  go/vt/vtorc/discovery/funcs.go
  go/vt/vtorc/discovery/queue.go
  go/vt/vtorc/discovery/queue_aggregated_stats.go
  go/vt/vtorc/discovery/queue_test.go
  go/vt/vtorc/inst/instance_utils.go
  go/vt/vtorc/inst/instance_utils_test.go
  go/vt/vtorc/inst/oracle_gtid_set.go
  go/vt/vtorc/inst/oracle_gtid_set_entry.go
  go/vt/vtorc/inst/oracle_gtid_set_test.go
  go/vt/vtorc/inst/tablet_dao.go
  go/vt/vtorc/inst/tablet_dao_test.go
  go/vt/vtorc/logic/keyspace_shard_discovery.go
  go/vt/vtorc/logic/tablet_discovery.go
  go/vt/vtorc/logic/topology_recovery.go
  go/vt/vtorc/logic/vtorc.go
  go/vt/vtorc/metrics/query/aggregated.go
  go/vt/vtorc/process/election_dao.go
  go/vt/vtorc/util/token.go
Labels: upstream-backport, cla:missing, v20-backport, v19, v22-backport, Component: VTOrc

#621 `slack-19.0`: re-backport tweaks from vitessio/vitess#17911
  go/vt/vtorc/inst/shard_dao.go
  go/vt/vtorc/inst/shard_dao_test.go
  go/vt/vtorc/inst/tablet_dao.go
  go/vt/vtorc/inst/tablet_dao_test.go
  go/vt/vtorc/logic/keyspace_shard_discovery.go
  go/vt/vtorc/logic/tablet_discovery.go
Labels: upstream-backport, v19, v22-backport

#622 `slack 21.0`: backport v22 VTOrc improvements, part 2
  go/flags/endtoend/vtorc.txt
  go/vt/vtorc/config/config.go
  go/vt/vtorc/db/generate_base.go
  go/vt/vtorc/discovery/queue.go
  go/vt/vtorc/discovery/queue_test.go
  go/vt/vtorc/inst/instance_dao.go
  go/vt/vtorc/inst/shard_dao.go
  go/vt/vtorc/inst/shard_dao_test.go
  go/vt/vtorc/inst/tablet_dao.go
  go/vt/vtorc/inst/tablet_dao_test.go
  go/vt/vtorc/logic/keyspace_shard_discovery.go
  go/vt/vtorc/logic/keyspace_shard_discovery_test.go
  go/vt/vtorc/logic/tablet_discovery.go
  go/vt/vtorc/logic/topology_recovery.go
  go/vt/vtorc/logic/vtorc.go
Labels: upstream-backport, cla:missing, v22-backport, Component: VTOrc, v21

#625 Increase health check channel buffer (#17821)
  go/vt/discovery/healthcheck.go
  go/vt/discovery/healthcheck_test.go
Labels: cla:missing

#627 backport 15395: Allow for automatic resume after Reshard across VStreams (#1…
  go/test/endtoend/vreplication/vreplication_test.go
  go/test/endtoend/vreplication/vstream_test.go
  go/vt/topo/faketopo/faketopo.go
  go/vt/vtgate/vstream_manager.go
  go/vt/vtgate/vstream_manager_test.go
  test/config.json
Labels: upstream-backport, cla:missing, v20-backport

#585 VTGate VStream [Backport]: Ensure Reasonable Delivery Time for Reshard Journal Events
  examples/local/vstream_client.go
  go/test/endtoend/vreplication/vstream_test.go
  go/vt/vtctl/workflow/traffic_switcher.go
  go/vt/vtgate/vstream_manager.go
Labels: v19-backport
